[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]

[tool.mypy]
ignore_missing_imports = true
strict = true
exclude = "^tests/.*.py|venv"

[tool.coverage.run]
command_line = "-m pytest"
omit = ["tests/*.py", "setup.py"]

[tool.coverage.report]
show_missing = true
fail_under = 100
